# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Task.create(name: "Channel", description: "Upload CSV file containing Channel Data")
Task.create(name: "National", description: "Upload CSV file containing National Data")
Task.create(name: "Toronto", description: "Upload CSV file containing Toronto Data")
Task.create(name: "Calgary", description: "Upload CSV file containing Calgary Data")
Task.create(name: "Edmonton", description: "Upload CSV file containing Edmonton Data")
Task.create(name: "Vancouver", description: "Upload CSV file containing Vancouver Data")

Channel.create(channel_name: "APTN HD+", classification: "Specialty" , ownership: "Aboriginal Peoples Television Network" )
Channel.create(channel_name: "APTN+", classification: "Specialty" , ownership: "Aboriginal Peoples Television Network" )
Channel.create(channel_name: "ATPN-N", classification: "Specialty" , ownership: "Aboriginal Peoples Television Network" )
Channel.create(channel_name: "AMI-tv+", classification: "Specialty" , ownership: "Accessible Media Inc" )
Channel.create(channel_name: "Super Channel 1+", classification: "Pay Specialty" , ownership: "Allarco Entertainment" )
Channel.create(channel_name: "Super Channel 2+", classification: "Pay Specialty" , ownership: "Allarco Entertainment" )
Channel.create(channel_name: "Super Channel 3+", classification: "Pay Specialty" , ownership: "Allarco Entertainment" )
Channel.create(channel_name: "Super Channel 4+", classification: "Pay Specialty" , ownership: "Allarco Entertainment" )
Channel.create(channel_name: "Super Channel HD 2+", classification: "Pay Specialty" , ownership: "Allarco Entertainment" )
Channel.create( channel_name: "AMC+", classification: "US Specialty" , ownership: "AMC Networks")
Channel.create( channel_name: "Independent Film channel US", classification: "US Specialty" , ownership: "AMC Networks")
Channel.create( channel_name: "Sundance", classification: "US Specialty" , ownership: "AMC Networks")
Channel.create( channel_name: "TV Asia", classification: "US Specialty" , ownership: "Asian Star Broadcasting")
Channel.create( channel_name: "ATN Cricket Plus Channel", classification: "Pay Specialty" , ownership: "Asian Television Network")
Channel.create( channel_name: "Baby First TV (English)", classification: "US Specialty" , ownership: "Baby First TV")
Channel.create( channel_name: "Baby First TV (French)", classification: "US Specialty" , ownership: "Baby First TV")
Channel.create( channel_name: "Baby First TV (Spanish)", classification: "US Specialty" , ownership: "Baby First TV")
Channel.create( channel_name: "Animal Planet+", classification: "Specialty" , ownership: "Bell Media")
Channel.create( channel_name: "BNN Business News Network+", classification: "Specialty" , ownership: "Bell Media")
Channel.create( channel_name: "Bravo+", classification: "Specialty" , ownership: "Bell Media")
Channel.create( channel_name: "Comedy+", classification: "Specialty" , ownership: "Bell Media")
Channel.create( channel_name: "CP24 Ontario+", classification: "Conventional" , ownership: "Bell Media")
Channel.create( channel_name: "CTV Calgary (CFCN)+", classification: "Conventional" , ownership: "Bell Media")
Channel.create( channel_name: "CTV Edmonton (CFRN)+", classification: "Conventional" , ownership: "Bell Media")
Channel.create( channel_name: "CTV News Channel+", classification: "Specialty" , ownership: "Bell Media")
Channel.create( channel_name: "CTV Ontario", classification: "Conventional" , ownership: "Bell Media")
Channel.create( channel_name: "CTV Total", classification: "Conventional" , ownership: "Bell Media")
Channel.create( channel_name: "CTV Two (Alberta)+", classification: "Conventional" , ownership: "Bell Media")
Channel.create( channel_name: "CTV Two Ontario", classification: "Conventional" , ownership: "Bell Media")
Channel.create( channel_name: "CTV Two Total", classification: "Conventional" , ownership: "Bell Media")
Channel.create( channel_name: "CTV Two Vancouver (CIVI)+", classification: "Conventional" , ownership: "Bell Media")
Channel.create( channel_name: "CTV Vancouver (CIVT)+", classification: "Conventional" , ownership: "Bell Media")
Channel.create( channel_name: "Discovery Science+", classification: "Specialty" , ownership: "Bell Media")
Channel.create( channel_name: "Discovery World+", classification: "Specialty" , ownership: "Bell Media")
Channel.create( channel_name: "Discovery+", classification: "Specialty" , ownership: "Bell Media")
Channel.create( channel_name: "Disney Junior Eng+", classification: "Pay Specialty" , ownership: "Bell Media")
Channel.create( channel_name: "Disney XD+", classification: "Specialty" , ownership: "Bell Media")
Channel.create( channel_name: "E!+", classification: "Specialty" , ownership: "Bell Media")
Channel.create( channel_name: "ESPN Classic Canada", classification: "Sports" , ownership: "Bell Media")
Channel.create( channel_name: "ESPN Classic Canada+", classification: "Sports" , ownership: "Bell Media")
Channel.create( channel_name: "Family+", classification: "Pay Specialty" , ownership: "Bell Media")
Channel.create( channel_name: "HBO Canada+", classification:"Pay Specialty" , ownership: "Bell Media")
Channel.create( channel_name: "Investigation Discovery+", classification: "Specialty" , ownership:"Bell Media")
Channel.create( channel_name: "M (TMN1)+", classification: "Pay Specialty" , ownership: "Bell Media")
Channel.create( channel_name: "M Excess (TMN3)+", classification: "Pay Specialty" , ownership: "Bell Media")
Channel.create( channel_name: "M Fest (TMN5)+", classification: "Pay Specialty" , ownership: "Bell Media")
Channel.create( channel_name: "M Fun (TMN4)+", classification: "Pay Specialty" , ownership: "Bell Media")
Channel.create( channel_name: "MTV+", classification: "Specialty" , ownership: "Bell Media")
Channel.create( channel_name: "MTV2+", classification: "specialty" , ownership: "Bell Media")
Channel.create( channel_name: "MuchMore+", classification: "Specialty" , ownership: "Bell Media")
Channel.create( channel_name: "MuchMusic+", classification: "Specialty" , ownership: "Bell Media")
Channel.create( channel_name: "NHL Network+", classification: "Sports" , ownership: "Bell Media")
Channel.create( channel_name: "RDS+", classification: "Sports" , ownership: "Bell Media")
Channel.create( channel_name: "RDS2+", classification: "Sports" , ownership: "Bell Media")
Channel.create( channel_name: "Space+", classification: "Specialty" , ownership: "Bell Media")
Channel.create( channel_name: "Teletoon Eng+", classification: "Specialty" , ownership: "Bell Media")
Channel.create( channel_name: "Teletoon Retro Eng+", classification: "Specialty" , ownership: "Bell Media")
Channel.create( channel_name: "TMN Encore 2+", classification: "Pay Specialty" , ownership: "Bell Media")
Channel.create( channel_name: "TMN Encore+", classification: "Pay Specialty" , ownership: "Bell Media")
Channel.create( channel_name: "TSN+", classification: "Sports" , ownership: "Bell Media")
Channel.create( channel_name: "TSN2+", classification: "Sports" , ownership: "Bell Media")
Channel.create( channel_name: "Bloomberg TV US", classification: "US Specialty" , ownership: "Bloomberg L.P.")
Channel.create( channel_name: "Travel & Escape+", classification: "Specialty" , ownership: "Blue Ant Media")
Channel.create( channel_name: "CBC Calgary (CBRT)+", classification: "Conventional" , ownership: "CBC")
Channel.create( channel_name: "CBC Edmonton (CBXT)+", classification: "Conventional" , ownership: "CBC")
Channel.create( channel_name: "CBC News Network+", classification: "Specialty" , ownership: "CBC")
Channel.create( channel_name: "CBC Ontario", classification: "Conventional" , ownership: "CBC")
Channel.create( channel_name: "CBC Total", classification: "Conventional" , ownership: "CBC")
Channel.create( channel_name: "CBC Vancouver (CBUT)+", classification: "Conventional" , ownership: "CBC")
Channel.create( channel_name: "Documentary+", classification: "Specialty" , ownership: "CBC")
Channel.create( channel_name: "CBS College Sports Network", classification: "US Specialty" , ownership: "CBS Corporation")
Channel.create( channel_name: "KIRO+", classification: "US Conventional" , ownership: "CBS Corporation")
Channel.create( channel_name: "KSTW+", classification: "US Conventional" , ownership: "CBS Corporation")
Channel.create( channel_name: "Showtime", classification: "US Specialty" , ownership: "CBS Corporation")
Channel.create( channel_name: "WCAX+", classification: "US Conventional" , ownership: "CBS Corporation")
Channel.create( channel_name: "WGN+", classification: "US Conventional" , ownership: "CBS Corporation")
Channel.create( channel_name: "WIVB+", classification: "US Conventional" , ownership: "CBS Corporation")
Channel.create( channel_name: "WNLO+", classification: "US Conventional" , ownership: "CBS Corporation")
Channel.create( channel_name: "WTOL", classification: "US Conventional" , ownership: "CBS Corporation")
Channel.create( channel_name: "WVNY+", classification: "US Conventional" , ownership: "CBS Corporation")
Channel.create( channel_name: "WWJ+", classification: "US Conventional" , ownership: "CBS Corporation")
Channel.create( channel_name: "WWTV", classification: "US Conventional" , ownership: "CBS Corporation")
Channel.create( channel_name: "CHCH+", classification: "Conventional" , ownership: "Channel Zero")
Channel.create( channel_name: "CHEK+", classification: "Conventional" , ownership: "CHEK Media Group")
Channel.create( channel_name: "ABC Spark+", classification: "Specialty" , ownership: "Corus Entertainment")
Channel.create( channel_name: "Cartoon Network+", classification: "Specialty" , ownership: "Corus Entertainment")
Channel.create( channel_name: "CMT+", classification: "Specialty" , ownership: "Corus Entertainment")
Channel.create( channel_name: "Cosmo TV+", classification: "Specialty" , ownership: "Corus Entertainment")
Channel.create( channel_name: "Dusk+", classification: "Specialty", ownership: "Corus Entertainment")
Channel.create( channel_name: "Encour Ave 2 (MovieMax2)", classification: "Pay Specialty", ownership: "Corus Entertainment")
Channel.create( channel_name: "Encour Ave+", classification: "Pay Specialty", ownership: "Corus Entertainment")
Channel.create( channel_name: "MC 2+", classification: "Pay Specialty", ownership: "Corus Entertainment")
Channel.create( channel_name: "MC 3", classification: "Pay Specialty", ownership: "Corus Entertainment")
Channel.create( channel_name: "Movie Central HD", classification: "Pay Specialty", ownership: "Corus Entertainment")
Channel.create( channel_name: "Movie Central+", classification: "Pay Specialty", ownership: "Corus Entertainment")
Channel.create( channel_name: "Nickelodeon+", classification: "Specialty", ownership: "Corus Entertainment")
Channel.create( channel_name: "OWN+", classification: "Specialty", ownership: "Corus Entertainment")
Channel.create( channel_name: "Treehouse+", classification: "Specialty", ownership: "Corus Entertainment")
Channel.create( channel_name: "W Movies+", classification: "Specialty", ownership: "Corus Entertainment")
Channel.create( channel_name: "W Network+", classification: "Specialty", ownership: "Corus Entertainment")
Channel.create( channel_name: "YTV+", classification: "Specialty", ownership: "Corus Entertainment")
Channel.create( channel_name: "CTS Calgary (CKCS)+", classification: "Specialty", ownership: "Crossroads Christian Communication")
Channel.create( channel_name: "CTS Edmonton (CKES)+", classification: "Specialty", ownership: "Crossroads Christian Communication")
Channel.create( channel_name: "CTS Toronto+", classification: "Specialty", ownership: "Crossroads Christian Communication")
Channel.create( channel_name: "Animal Planet US", classification: "US Specialty", ownership: "Discovery Communications")
Channel.create( channel_name: "Discovery People", classification: "US Specialty", ownership: "Discovery Communications")
Channel.create( channel_name: "Military Channel", classification: "US Specialty", ownership: "Discovery Communications")
Channel.create( channel_name: "TLC+", classification: "US Specialty", ownership: "Discovery Communications")
Channel.create( channel_name: "A&E+", classification: "US Specialty", ownership: "Disney-ABC Television Group")
Channel.create( channel_name: "Classic Sports Network", classification: "US Specialty", ownership: "Disney-ABC Television Group")
Channel.create( channel_name: "Disney", classification: "US Specialty", ownership: "Disney-ABC Television Group")
Channel.create( channel_name: "ESPN", classification: "US Specialty", ownership: "Disney-ABC Television Group")
Channel.create( channel_name: "Family Channel US", classification: "US Specialty", ownership: "Disney-ABC Television Group")
Channel.create( channel_name: "History US", classification: "US Specialty", ownership: "Disney-ABC Television Group")
Channel.create( channel_name: "KOMO+", classification: "US Conventional", ownership: "Disney-ABC Television Group")
Channel.create( channel_name: "KREM+", classification: "US Conventional", ownership: "Disney-ABC Television Group")
Channel.create( channel_name: "KXLY+", classification: "US Conventional", ownership: "Disney-ABC Television Group")
Channel.create( channel_name: "Lifetime US", classification: "US Specialty", ownership: "Disney-ABC Television Group")
Channel.create( channel_name: "WCVB+", classification: "US Conventional", ownership: "Disney-ABC Television Group")
Channel.create( channel_name: "WDAZ+", classification: "US Conventional", ownership: "Disney-ABC Television Group")
Channel.create( channel_name: "WKBW+", classification: "US Conventional", ownership: "Disney-ABC Television Group")
Channel.create( channel_name: "New England Sports Network", classification: "US Specialty", ownership: "Fenway Sports Group")
Channel.create( channel_name: "Big Ten Network+", classification: "US Specialty", ownership: "Fox Entertainment Group")
Channel.create( channel_name: "Fox News US+", classification: "US Specialty", ownership: "Fox Entertainment Group") 
Channel.create( channel_name: "Fox Sports US+", classification: "US Specialty", ownership: "Fox Entertainment Group") 
Channel.create( channel_name: "KAYU+", classification: "US Conventional", ownership: "Fox Entertainment Group") 
Channel.create( channel_name: "KCPQ+", classification: "US Conventional", ownership: "Fox Entertainment Group") 
Channel.create( channel_name: "Movie Channel US", classification: "US Specialty", ownership: "Fox Entertainment Group")
Channel.create( channel_name: "Speed+", classification: "US Specialty", ownership: "Fox Entertainment Group") 
Channel.create( channel_name: "WFFF+", classification: "US Conventional", ownership: "Fox Entertainment Group") 
Channel.create( channel_name: "WFQX+", classification: "US Conventional", ownership: "Fox Entertainment Group") 
Channel.create( channel_name: "WJBK+", classification: "US Conventional", ownership: "Fox Entertainment Group") 
Channel.create( channel_name: "WNYO+", classification: "US Conventional", ownership: "Fox Entertainment Group")
Channel.create( channel_name: "WUHF+", classification: "US Conventional", ownership: "Fox Entertainment Group") 
Channel.create( channel_name: "WUTV+", classification: "US Conventional", ownership: "Fox Entertainment Group")
Channel.create( channel_name: "HBO - Home Box Office", classification: "US Specialty", ownership: "Home Box Office")
Channel.create( channel_name: "Home Shopping US", classification: "US Specialty", ownership: "Home Shopping Channel")
Channel.create( channel_name: "Knowledge BC (CKNO)+", classification: "Specialty", ownership: "Knowledge Network Corporation (BC Government)")
Channel.create( channel_name: "Quality Value Convenience", classification: "US Specialty", ownership: "Liberty Media")
Channel.create( channel_name: "Playboy", classification: "US Specialty", ownership: "Manwin")
Channel.create( channel_name: "Dandana TV (Egypt)", classification: "US Specialty", ownership: "n/a")
Channel.create( channel_name: "Empire Sports", classification: "US Specialty", ownership: "n/a")
Channel.create( channel_name: "Eurochannel", classification: "US Specialty", ownership: "n/a")
Channel.create( channel_name: "Flix", classification: "US Specialty", ownership: "n/a")
Channel.create( channel_name: "KVOS+", classification: "US Conventional", ownership: "Memorable Entertainment Television")
Channel.create( channel_name: "Russian (ABC)", classification: "US Specialty", ownership: "n/a")
Channel.create( channel_name: "Star East US", classification: "US Specialty", ownership: "n/a")
Channel.create( channel_name: "Sunshine Net", classification: "US Specialty", ownership: "n/a")
Channel.create( channel_name: "WTBD", classification: "US Specialty", ownership: "n/a")
Channel.create( channel_name: "NASA", classification: "US Specialty", ownership: "Nasa")
Channel.create( channel_name: "CSPAN 1", classification: "US Specialty", ownership: "National Cable Satellite Corporation")
Channel.create( channel_name: "NFL Network", classification: "US Specialty", ownership: "National Football League")
Channel.create( channel_name: "Bravo US", classification: "US Specialty", ownership: "NBC Universal")
Channel.create( channel_name: "CNBC", classification: "US Specialty", ownership: "NBC Universal")
Channel.create( channel_name: "Golf+", classification: "US Specialty", ownership: "NBC Universal")
Channel.create( channel_name: "Home Team Sports", classification: "US Specialty", ownership: "NBC Universal")
Channel.create( channel_name: "KARE+", classification: "US Conventional", ownership: "NBC Universal")
Channel.create( channel_name: "KHQ+", classification: "US Conventional", ownership: "NBC Universal")
Channel.create( channel_name: "KING+", classification: "US Conventional", ownership: "NBC Universal")
Channel.create( channel_name: "MSNBC US", classification: "US Specialty", ownership: "NBC Universal")
Channel.create( channel_name: "OLN US", classification: "US Specialty", ownership: "NBC Universal")
Channel.create( channel_name: "Sci Fi", classification: "US Specialty", ownership: "NBC Universal")
Channel.create( channel_name: "USA Network", classification: "US Specialty", ownership: "NBC Universal")
Channel.create( channel_name: "WDIV+", classification: "US Conventional", ownership: "NBC Universal")
Channel.create( channel_name: "WGRZ+", classification: "US Conventional", ownership: "NBC Universal")
Channel.create( channel_name: "WPTZ+", classification: "US Conventional", ownership: "NBC Universal")
Channel.create( channel_name: "New Tang Dynasty", classification: "US Specialty", ownership: "New Tang Dynasty")
Channel.create( channel_name: "KCTS+", classification: "US Conventional", ownership: "PBS")
Channel.create( channel_name: "KSPS+", classification: "US Conventional", ownership: "PBS")
Channel.create( channel_name: "WCFE+", classification: "US Conventional", ownership: "PBS")
Channel.create( channel_name: "WETK+", classification: "US Conventional", ownership: "PBS")
Channel.create( channel_name: "WNED+", classification: "US Conventional", ownership: "PBS")
Channel.create( channel_name: "WTVS+", classification: "US Conventional", ownership: "PBS")
Channel.create( channel_name: "Weather US", classification: "US Specialty", ownership: "Pelmorex Media Inc.")
Channel.create( channel_name: "Weather+", classification: "Specialty", ownership: "Pelmorex Media Inc.")
Channel.create( channel_name: "Sun News+", classification: "Specialty", ownership: "Quebecor Media")
Channel.create( channel_name: "TVA Sports+", classification: "Sports", ownership: "Quebecor Media")
Channel.create( channel_name: "bio+", classification: "Specialty", ownership: "Rogers Media")
Channel.create( channel_name: "City Calgary (CKAL)+", classification: "Conventional", ownership: "Rogers Media")
Channel.create( channel_name: "City Edmonton (CKEM)+", classification: "Conventional", ownership: "Rogers Media")
Channel.create( channel_name: "City Ontario (CITY)+", classification: "Conventional", ownership: "Rogers Media")
Channel.create( channel_name: "City Total", classification: "Conventional", ownership: "Rogers Media")
Channel.create( channel_name: "City Vancouver (CKVU)+", classification: "Conventional", ownership: "Rogers Media")
Channel.create( channel_name: "FX Canada+", classification: "Specialty", ownership: "Rogers Media")
Channel.create( channel_name: "G4+", classification: "Specialty", ownership: "Rogers Media")
Channel.create( channel_name: "OLN+", classification: "Specialty", ownership: "Rogers Media")
Channel.create( channel_name: "OMNI 1 Ontario (CFMT)+", classification: "Conventional", ownership: "Rogers Media")
Channel.create( channel_name: "OMNI 2 Ontario (CJMT)+", classification: "Conventional", ownership: "Rogers Media")
Channel.create( channel_name: "OMNI BC (CHNM)+", classification: "Conventional", ownership: "Rogers Media")
Channel.create( channel_name: "OMNI Calgary (CJCO)+", classification: "Conventional", ownership: "Rogers Media")
Channel.create( channel_name: "Omni Edmonton (CJEO)+", classification: "Conventional", ownership: "Rogers Media")
Channel.create( channel_name: "Sportsnet East+", classification: "Sports", ownership: "Rogers Media")
Channel.create( channel_name: "Sportsnet National+", classification: "Sports", ownership: "Rogers Media")
Channel.create( channel_name: "Sportsnet Ont+", classification: "Sports", ownership: "Rogers Media")
Channel.create( channel_name: "Sportsnet Pac+", classification: "Sports", ownership: "Rogers Media")
Channel.create( channel_name: "Sportsnet West+", classification: "Sports", ownership: "Rogers Media")
Channel.create( channel_name: "Sportsnet360+", classification: "Sports", ownership: "Rogers Media")
Channel.create( channel_name: "SportsnetOne+", classification: "Sports", ownership: "Rogers Media")
Channel.create( channel_name: "City News Channel+", classification: "Specialty", ownership: "Rogers Media")
Channel.create( channel_name: "HGTV US", classification: "US Specialty", ownership: "Scripps Networks Inc.")
Channel.create( channel_name: "Travel US", classification: "US Specialty", ownership: "Scripps Networks Inc.")
Channel.create( channel_name: "Action+", classification: "Specialty", ownership: "Shaw Media")
Channel.create( channel_name: "BBC Canada+", classification: "Specialty", ownership: "Shaw Media")
Channel.create( channel_name: "BC1+", classification: "Specialty", ownership: "Shaw Media")
Channel.create( channel_name: "Deja View+", classification: "Specialty", ownership: "Shaw Media")
Channel.create( channel_name: "diy network+", classification: "Specialty", ownership: "Shaw Media")
Channel.create( channel_name: "Food Network+", classification: "Specialty", ownership: "Shaw Media")
Channel.create( channel_name: "Fox News Canada", classification: "US Specialty", ownership: "Shaw Media")
Channel.create( channel_name: "Fox Sports Canada", classification: "Sports", ownership: "Shaw Media")
Channel.create( channel_name: "Global BC (CHAN/CHBC)+", classification: "Conventional", ownership: "Shaw Media")
Channel.create( channel_name: "Global Calgary (CICT/CISA)+", classification: "Conventional", ownership: "Shaw Media")
Channel.create( channel_name: "Global Edmonton (CITV)+", classification: "Conventional", ownership: "Shaw Media")
Channel.create( channel_name: "Global Ontario (CIII)+", classification: "Conventional", ownership: "Shaw Media")
Channel.create( channel_name: "Global Reality Channel+", classification: "Specialty", ownership: "Shaw Media")
Channel.create( channel_name: "Global Total", classification: "Conventional", ownership: "Shaw Media")
Channel.create( channel_name: "H2+", classification: "Specialty", ownership: "Shaw Media")
Channel.create( channel_name: "HGTV+", classification: "Specialty", ownership: "Shaw Media")
Channel.create( channel_name: "History+", classification: "Specialty", ownership: "Shaw Media")
Channel.create( channel_name: "IFC+", classification: "Specialty", ownership: "Shaw Media")
Channel.create( channel_name: "Lifetime+", classification: "Specialty", ownership: "Shaw Media")
Channel.create( channel_name: "MovieTime+", classification: "Specialty", ownership: "Shaw Media")
Channel.create( channel_name: "Mystery+", classification: "Specialty", ownership: "Shaw Media")
Channel.create( channel_name: "National Geographic+", classification: "Specialty", ownership: "Shaw Media")
Channel.create( channel_name: "Showcase+", classification: "Specialty", ownership: "Shaw Media")
Channel.create( channel_name: "Slice+", classification: "Specialty", ownership: "Shaw Media")
Channel.create( channel_name: "Tvtropolis+", classification: "Specialty", ownership: "Shaw Media")
Channel.create( channel_name: "GSN", classification: "US Specialty", ownership: "Sony Pictures Television")
Channel.create( channel_name: "Madison Square Gardens", classification: "US Specialty", ownership: "The Madison Square Garden Company")
Channel.create( channel_name:"Cartoon Net US", classification:"US Specialty", ownership:"Time Warner")
Channel.create( channel_name:"CineMax", classification:"US Specialty", ownership:"Time Warner")
Channel.create( channel_name:"CNN International", classification:"US Specialty", ownership:"Time Warner")
Channel.create( channel_name:"CNN+", classification:"US Specialty", ownership:"Time Warner")
Channel.create( channel_name:"Headline News", classification:"US Specialty", ownership:"Time Warner")
Channel.create( channel_name:"Peachtree TV+", classification:"US Conventional", ownership:"Time Warner")
Channel.create( channel_name:"tru TV", classification:"US Specialty", ownership:"Time Warner")
Channel.create( channel_name:"Turner Classic Movies", classification:"US Specialty", ownership:"Time Warner")
Channel.create( channel_name:"Turner Network", classification:"US Specialty", ownership:"Time Warner")
Channel.create( channel_name:"Trinity", classification:"US Specialty", ownership:"Trinity Broadcastiong Network")
Channel.create( channel_name:"Univision", classification:"US Specialty", ownership:"Univision Communications")
Channel.create( channel_name:"Encore US", classification:"US Specialty", ownership:"Starz")
Channel.create( channel_name:"Entertainment TV", classification:"US Specialty", ownership:"NBC Universal")
Channel.create( channel_name:"Eternal Word", classification:"US Specialty", ownership:"Eternal Word Television Network")
Channel.create( channel_name:"GALAVISION", classification:"US Specialty", ownership:"Univision Communications")
Channel.create( channel_name:"HDNet", classification:"US Specialty", ownership:"HDNet Inc.")
Channel.create( channel_name:"Health", classification:"US Specialty", ownership:"n/a")
Channel.create( channel_name:"MuchMusic US", classification:"US Specialty", ownership:"n/a")
Channel.create( channel_name:"All News Channel", classification:"US Specialty", ownership:"Viacom Media Networks")
Channel.create( channel_name:"BET", classification:"US Specialty", ownership:"Viacom Media Networks")
Channel.create( channel_name:"Comedy Central", classification:"US Specialty", ownership:"Viacom Media Networks")
Channel.create( channel_name:"Country Music US", classification:"US Specialty", ownership:"Viacom Media Networks")
Channel.create( channel_name:"Music TV", classification:"US Specialty", ownership:"Viacom Media Networks")
Channel.create( channel_name:"Nickelodeon US", classification:"US Specialty", ownership:"Viacom Media Networks")
Channel.create( channel_name:"Noggin - Educ US", classification:"US Specialty", ownership:"Viacom Media Networks")
Channel.create( channel_name:"Spike+", classification:"US Specialty", ownership:"Viacom Media Networks")
Channel.create( channel_name:"TV Land US", classification:"US Specialty", ownership:"Viacom Media Networks")
Channel.create( channel_name:"Video Hits 1", classification:"US Specialty", ownership:"Viacom Media Networks")
Channel.create( channel_name:"Joy TV 10 BC (CHNU)+", classification:"Specialty", ownership:"ZoomerMedia")
Channel.create( channel_name:"Vision+", classification:"Specialty", ownership:"ZoomerMedia")
Channel.create( channel_name:"Dtour+", classification:"Specialty", ownership:"Shaw Media")
Channel.create( channel_name:"Movie Central 1+", classification:"Pay Specialty", ownership:"Bell Media")
Channel.create( channel_name:"Much+", classification:"Specialty", ownership:"Bell Media")
Channel.create( channel_name:"M3+", classification:"Specialty", ownership:"Bell Media")
